/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.bank.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Bank service. Represents a row in the &quot;BANK_Bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demo.bank.model.impl.BankModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demo.bank.model.impl.BankImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Bank
 * @generated
 */
@ProviderType
public interface BankModel extends BaseModel<Bank> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bank model instance should use the {@link Bank} interface instead.
	 */

	/**
	 * Returns the primary key of this bank.
	 *
	 * @return the primary key of this bank
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bank.
	 *
	 * @param primaryKey the primary key of this bank
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bank.
	 *
	 * @return the uuid of this bank
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this bank.
	 *
	 * @param uuid the uuid of this bank
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the bank ID of this bank.
	 *
	 * @return the bank ID of this bank
	 */
	public long getBankId();

	/**
	 * Sets the bank ID of this bank.
	 *
	 * @param bankId the bank ID of this bank
	 */
	public void setBankId(long bankId);

	/**
	 * Returns the bank name of this bank.
	 *
	 * @return the bank name of this bank
	 */
	@AutoEscape
	public String getBankName();

	/**
	 * Sets the bank name of this bank.
	 *
	 * @param bankName the bank name of this bank
	 */
	public void setBankName(String bankName);

	/**
	 * Returns the bank address of this bank.
	 *
	 * @return the bank address of this bank
	 */
	@AutoEscape
	public String getBankAddress();

	/**
	 * Sets the bank address of this bank.
	 *
	 * @param bankAddress the bank address of this bank
	 */
	public void setBankAddress(String bankAddress);

	@Override
	public Bank cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}