/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.bank.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Salary service. Represents a row in the &quot;BANK_Salary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demo.bank.model.impl.SalaryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demo.bank.model.impl.SalaryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Salary
 * @generated
 */
@ProviderType
public interface SalaryModel extends BaseModel<Salary> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a salary model instance should use the {@link Salary} interface instead.
	 */

	/**
	 * Returns the primary key of this salary.
	 *
	 * @return the primary key of this salary
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this salary.
	 *
	 * @param primaryKey the primary key of this salary
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this salary.
	 *
	 * @return the uuid of this salary
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this salary.
	 *
	 * @param uuid the uuid of this salary
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the salary ID of this salary.
	 *
	 * @return the salary ID of this salary
	 */
	public long getSalaryId();

	/**
	 * Sets the salary ID of this salary.
	 *
	 * @param salaryId the salary ID of this salary
	 */
	public void setSalaryId(long salaryId);

	/**
	 * Returns the employee ID of this salary.
	 *
	 * @return the employee ID of this salary
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this salary.
	 *
	 * @param employeeId the employee ID of this salary
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the amount of this salary.
	 *
	 * @return the amount of this salary
	 */
	public double getAmount();

	/**
	 * Sets the amount of this salary.
	 *
	 * @param amount the amount of this salary
	 */
	public void setAmount(double amount);

	/**
	 * Returns the currency of this salary.
	 *
	 * @return the currency of this salary
	 */
	@AutoEscape
	public String getCurrency();

	/**
	 * Sets the currency of this salary.
	 *
	 * @param currency the currency of this salary
	 */
	public void setCurrency(String currency);

	/**
	 * Returns the payment date of this salary.
	 *
	 * @return the payment date of this salary
	 */
	public Date getPaymentDate();

	/**
	 * Sets the payment date of this salary.
	 *
	 * @param paymentDate the payment date of this salary
	 */
	public void setPaymentDate(Date paymentDate);

	@Override
	public Salary cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}