/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package student.headless.builder.model.impl;

import student.headless.builder.model.student;
import student.headless.builder.service.studentLocalServiceUtil;

/**
 * The extended model base implementation for the student service. Represents a row in the &quot;STU_student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link studentImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see studentImpl
 * @see student
 * @generated
 */
public abstract class studentBaseImpl
	extends studentModelImpl implements student {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a student model instance should use the <code>student</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			studentLocalServiceUtil.addstudent(this);
		}
		else {
			studentLocalServiceUtil.updatestudent(this);
		}
	}

}