/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.org.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Department service. Represents a row in the &quot;ORG_Department&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.demo.org.model.impl.DepartmentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.demo.org.model.impl.DepartmentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department
 * @generated
 */
@ProviderType
public interface DepartmentModel extends BaseModel<Department> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a department model instance should use the {@link Department} interface instead.
	 */

	/**
	 * Returns the primary key of this department.
	 *
	 * @return the primary key of this department
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this department.
	 *
	 * @param primaryKey the primary key of this department
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this department.
	 *
	 * @return the uuid of this department
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this department.
	 *
	 * @param uuid the uuid of this department
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the department ID of this department.
	 *
	 * @return the department ID of this department
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this department.
	 *
	 * @param departmentId the department ID of this department
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the department no of this department.
	 *
	 * @return the department no of this department
	 */
	@AutoEscape
	public String getDepartmentNo();

	/**
	 * Sets the department no of this department.
	 *
	 * @param departmentNo the department no of this department
	 */
	public void setDepartmentNo(String departmentNo);

	/**
	 * Returns the department name of this department.
	 *
	 * @return the department name of this department
	 */
	@AutoEscape
	public String getDepartmentName();

	/**
	 * Sets the department name of this department.
	 *
	 * @param departmentName the department name of this department
	 */
	public void setDepartmentName(String departmentName);

	/**
	 * Returns the department address of this department.
	 *
	 * @return the department address of this department
	 */
	@AutoEscape
	public String getDepartmentAddress();

	/**
	 * Sets the department address of this department.
	 *
	 * @param departmentAddress the department address of this department
	 */
	public void setDepartmentAddress(String departmentAddress);

	/**
	 * Returns the department pin of this department.
	 *
	 * @return the department pin of this department
	 */
	public int getDepartmentPin();

	/**
	 * Sets the department pin of this department.
	 *
	 * @param departmentPin the department pin of this department
	 */
	public void setDepartmentPin(int departmentPin);

	/**
	 * Returns the employee ID of this department.
	 *
	 * @return the employee ID of this department
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this department.
	 *
	 * @param employeeId the employee ID of this department
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the bank ID of this department.
	 *
	 * @return the bank ID of this department
	 */
	public long getBankId();

	/**
	 * Sets the bank ID of this department.
	 *
	 * @param bankId the bank ID of this department
	 */
	public void setBankId(long bankId);

	@Override
	public Department cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}