/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.bank.model.impl;

import com.demo.bank.model.Bank;
import com.demo.bank.service.BankLocalServiceUtil;

/**
 * The extended model base implementation for the Bank service. Represents a row in the &quot;BANK_Bank&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BankImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BankImpl
 * @see Bank
 * @generated
 */
public abstract class BankBaseImpl extends BankModelImpl implements Bank {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bank model instance should use the <code>Bank</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BankLocalServiceUtil.addBank(this);
		}
		else {
			BankLocalServiceUtil.updateBank(this);
		}
	}

}