/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.bank.model.impl;

import com.demo.bank.model.Salary;
import com.demo.bank.service.SalaryLocalServiceUtil;

/**
 * The extended model base implementation for the Salary service. Represents a row in the &quot;BANK_Salary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalaryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalaryImpl
 * @see Salary
 * @generated
 */
public abstract class SalaryBaseImpl extends SalaryModelImpl implements Salary {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a salary model instance should use the <code>Salary</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SalaryLocalServiceUtil.addSalary(this);
		}
		else {
			SalaryLocalServiceUtil.updateSalary(this);
		}
	}

}