/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.demo.bank.model.impl;

import com.demo.bank.model.Salary;
import com.demo.bank.model.SalaryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Salary service. Represents a row in the &quot;BANK_Salary&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SalaryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SalaryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalaryImpl
 * @generated
 */
@JSON(strict = true)
public class SalaryModelImpl
	extends BaseModelImpl<Salary> implements SalaryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a salary model instance should use the <code>Salary</code> interface instead.
	 */
	public static final String TABLE_NAME = "BANK_Salary";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"salaryId", Types.BIGINT},
		{"employeeId", Types.BIGINT}, {"amount", Types.DOUBLE},
		{"currency_", Types.VARCHAR}, {"paymentDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("salaryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("amount", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("currency_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("paymentDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BANK_Salary (uuid_ VARCHAR(75) null,salaryId LONG not null primary key,employeeId LONG,amount DOUBLE,currency_ VARCHAR(75) null,paymentDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table BANK_Salary";

	public static final String ORDER_BY_JPQL = " ORDER BY salary.salaryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BANK_Salary.salaryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SALARYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SalaryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _salaryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSalaryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _salaryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Salary.class;
	}

	@Override
	public String getModelClassName() {
		return Salary.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Salary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Salary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Salary, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Salary)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Salary, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Salary, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Salary)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Salary, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Salary, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Salary, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Salary, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Salary, Object>>();

			attributeGetterFunctions.put("uuid", Salary::getUuid);
			attributeGetterFunctions.put("salaryId", Salary::getSalaryId);
			attributeGetterFunctions.put("employeeId", Salary::getEmployeeId);
			attributeGetterFunctions.put("amount", Salary::getAmount);
			attributeGetterFunctions.put("currency", Salary::getCurrency);
			attributeGetterFunctions.put("paymentDate", Salary::getPaymentDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Salary, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Salary, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Salary, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Salary, String>)Salary::setUuid);
			attributeSetterBiConsumers.put(
				"salaryId", (BiConsumer<Salary, Long>)Salary::setSalaryId);
			attributeSetterBiConsumers.put(
				"employeeId", (BiConsumer<Salary, Long>)Salary::setEmployeeId);
			attributeSetterBiConsumers.put(
				"amount", (BiConsumer<Salary, Double>)Salary::setAmount);
			attributeSetterBiConsumers.put(
				"currency", (BiConsumer<Salary, String>)Salary::setCurrency);
			attributeSetterBiConsumers.put(
				"paymentDate",
				(BiConsumer<Salary, Date>)Salary::setPaymentDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getSalaryId() {
		return _salaryId;
	}

	@Override
	public void setSalaryId(long salaryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_salaryId = salaryId;
	}

	@JSON
	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@JSON
	@Override
	public double getAmount() {
		return _amount;
	}

	@Override
	public void setAmount(double amount) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_amount = amount;
	}

	@JSON
	@Override
	public String getCurrency() {
		if (_currency == null) {
			return "";
		}
		else {
			return _currency;
		}
	}

	@Override
	public void setCurrency(String currency) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_currency = currency;
	}

	@JSON
	@Override
	public Date getPaymentDate() {
		return _paymentDate;
	}

	@Override
	public void setPaymentDate(Date paymentDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_paymentDate = paymentDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Salary.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Salary toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Salary>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SalaryImpl salaryImpl = new SalaryImpl();

		salaryImpl.setUuid(getUuid());
		salaryImpl.setSalaryId(getSalaryId());
		salaryImpl.setEmployeeId(getEmployeeId());
		salaryImpl.setAmount(getAmount());
		salaryImpl.setCurrency(getCurrency());
		salaryImpl.setPaymentDate(getPaymentDate());

		salaryImpl.resetOriginalValues();

		return salaryImpl;
	}

	@Override
	public Salary cloneWithOriginalValues() {
		SalaryImpl salaryImpl = new SalaryImpl();

		salaryImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		salaryImpl.setSalaryId(this.<Long>getColumnOriginalValue("salaryId"));
		salaryImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		salaryImpl.setAmount(this.<Double>getColumnOriginalValue("amount"));
		salaryImpl.setCurrency(
			this.<String>getColumnOriginalValue("currency_"));
		salaryImpl.setPaymentDate(
			this.<Date>getColumnOriginalValue("paymentDate"));

		return salaryImpl;
	}

	@Override
	public int compareTo(Salary salary) {
		long primaryKey = salary.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Salary)) {
			return false;
		}

		Salary salary = (Salary)object;

		long primaryKey = salary.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Salary> toCacheModel() {
		SalaryCacheModel salaryCacheModel = new SalaryCacheModel();

		salaryCacheModel.uuid = getUuid();

		String uuid = salaryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			salaryCacheModel.uuid = null;
		}

		salaryCacheModel.salaryId = getSalaryId();

		salaryCacheModel.employeeId = getEmployeeId();

		salaryCacheModel.amount = getAmount();

		salaryCacheModel.currency = getCurrency();

		String currency = salaryCacheModel.currency;

		if ((currency != null) && (currency.length() == 0)) {
			salaryCacheModel.currency = null;
		}

		Date paymentDate = getPaymentDate();

		if (paymentDate != null) {
			salaryCacheModel.paymentDate = paymentDate.getTime();
		}
		else {
			salaryCacheModel.paymentDate = Long.MIN_VALUE;
		}

		return salaryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Salary, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Salary, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Salary, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Salary)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Salary>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Salary.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _salaryId;
	private long _employeeId;
	private double _amount;
	private String _currency;
	private Date _paymentDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Salary, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Salary)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("salaryId", _salaryId);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("amount", _amount);
		_columnOriginalValues.put("currency_", _currency);
		_columnOriginalValues.put("paymentDate", _paymentDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("currency_", "currency");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("salaryId", 2L);

		columnBitmasks.put("employeeId", 4L);

		columnBitmasks.put("amount", 8L);

		columnBitmasks.put("currency_", 16L);

		columnBitmasks.put("paymentDate", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Salary _escapedModel;

}