/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.user.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Excel service. Represents a row in the &quot;CUSTOM_Excel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.user.model.impl.ExcelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.user.model.impl.ExcelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Excel
 * @generated
 */
@ProviderType
public interface ExcelModel extends BaseModel<Excel> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a excel model instance should use the {@link Excel} interface instead.
	 */

	/**
	 * Returns the primary key of this excel.
	 *
	 * @return the primary key of this excel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this excel.
	 *
	 * @param primaryKey the primary key of this excel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this excel.
	 *
	 * @return the uuid of this excel
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this excel.
	 *
	 * @param uuid the uuid of this excel
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the excel ID of this excel.
	 *
	 * @return the excel ID of this excel
	 */
	public long getExcelId();

	/**
	 * Sets the excel ID of this excel.
	 *
	 * @param excelId the excel ID of this excel
	 */
	public void setExcelId(long excelId);

	/**
	 * Returns the name of this excel.
	 *
	 * @return the name of this excel
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this excel.
	 *
	 * @param name the name of this excel
	 */
	public void setName(String name);

	/**
	 * Returns the address of this excel.
	 *
	 * @return the address of this excel
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this excel.
	 *
	 * @param address the address of this excel
	 */
	public void setAddress(String address);

	/**
	 * Returns the phone number of this excel.
	 *
	 * @return the phone number of this excel
	 */
	public long getPhoneNumber();

	/**
	 * Sets the phone number of this excel.
	 *
	 * @param phoneNumber the phone number of this excel
	 */
	public void setPhoneNumber(long phoneNumber);

	@Override
	public Excel cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}