/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package student.headless.builder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the student service. Represents a row in the &quot;STU_student&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>student.headless.builder.model.impl.studentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>student.headless.builder.model.impl.studentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see student
 * @generated
 */
@ProviderType
public interface studentModel extends BaseModel<student> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student model instance should use the {@link student} interface instead.
	 */

	/**
	 * Returns the primary key of this student.
	 *
	 * @return the primary key of this student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student.
	 *
	 * @param primaryKey the primary key of this student
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this student.
	 *
	 * @return the ID of this student
	 */
	public long getId();

	/**
	 * Sets the ID of this student.
	 *
	 * @param id the ID of this student
	 */
	public void setId(long id);

	/**
	 * Returns the name of this student.
	 *
	 * @return the name of this student
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this student.
	 *
	 * @param name the name of this student
	 */
	public void setName(String name);

	/**
	 * Returns the standard of this student.
	 *
	 * @return the standard of this student
	 */
	@AutoEscape
	public String getStandard();

	/**
	 * Sets the standard of this student.
	 *
	 * @param standard the standard of this student
	 */
	public void setStandard(String standard);

	@Override
	public student cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}