/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.dualdb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Professor service. Represents a row in the &quot;professors&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dualdb.model.impl.ProfessorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dualdb.model.impl.ProfessorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Professor
 * @generated
 */
@ProviderType
public interface ProfessorModel extends BaseModel<Professor> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a professor model instance should use the {@link Professor} interface instead.
	 */

	/**
	 * Returns the primary key of this professor.
	 *
	 * @return the primary key of this professor
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this professor.
	 *
	 * @param primaryKey the primary key of this professor
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this professor.
	 *
	 * @return the uuid of this professor
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this professor.
	 *
	 * @param uuid the uuid of this professor
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the p ID of this professor.
	 *
	 * @return the p ID of this professor
	 */
	public int getPId();

	/**
	 * Sets the p ID of this professor.
	 *
	 * @param pId the p ID of this professor
	 */
	public void setPId(int pId);

	/**
	 * Returns the p name of this professor.
	 *
	 * @return the p name of this professor
	 */
	@AutoEscape
	public String getPName();

	/**
	 * Sets the p name of this professor.
	 *
	 * @param pName the p name of this professor
	 */
	public void setPName(String pName);

	@Override
	public Professor cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}